services:
  - type: web
    name: flask-gemini-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - key: SECRET_KEY
        value: railway-secret-key-123
